# Math  1376: Programming for Data Science
---

## External activities for 02-Python-basics-lecture-part-c
---

**Expected time to completion: 1 hour**

In [2]:
import numpy as np

Below we make three arrays, `A`, `B`, and `C`, of different shapes.

In [3]:
# Creating the arrays (really matrices) used in this activity
A = np.reshape(range(1,7),(2,3))  # create a 2x3 array
B = np.reshape(range(1,7),(3,2))  # create a 3x2 array 
C = np.reshape(range(1,10),(3,3))  # create a 3x3 array
print(A, '\n\n', B, '\n\n', C)

[[1 2 3]
 [4 5 6]] 

 [[1 2]
 [3 4]
 [5 6]] 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


---

##  <mark>Activity 1: Some practice with array addition and transposes</mark> 

The following operations are undefined because the shapes cannot be [broadcast](https://numpy.org/doc/stable/user/basics.broadcasting.html) together because they do not have compatible shapes: `A+B`, `A+C`, and `B+C`. 

- In the code cell below, use the `transpose` method in `numpy` to do the following:

    - Add the transpose of `A` to `B` and print the result.
    
    - Add `A` to the transpose of `B` and print the result.
    
- In the Markdown cell that follows the code cell, explain the differences in results. Also, explain why it is impossible to add any transpose of `A` or `B` to `C`.

In [40]:

arr1  = np.transpose(A)
out_arr = np.add(arr1, B)  


barr1= np.transpose(B)
out_b_arr= np.add(A,barr1)


print(out_arr)
print("")
print(out_b_arr)
print("")

#The difference is that (A + (Transpose of B ))=  the transpose of ((transpose of A) + B)
#

[[ 2  6]
 [ 5  9]
 [ 8 12]]

[[ 2  5  8]
 [ 6  9 12]]



#A+C or B+C  matrix cannot be defined as the order of matrix A is 2×3 and the order of matrix B is 3X2. So, matrices A and B cannot be added together.

#The difference is that (A + (Transpose of B ))=  the transpose of ((transpose of A) + B)
#

End of Activity 1.

---

---

##  <mark>Activity 2: Some practice with operations and the axis parameter</mark> 

- In the code cell below, use the `mean` method in `numpy` along with `axis` parameters to do the following:

    - Add the array containing the mean of each row of `A` to the array containing the mean of each column of `B` and print the result. (The answer should be `[5., 9.]`)
    
    - Add the array containing the mean of each column of `A` to the array containing the mean of each row of `B` and print the result.
    
    - Add the array containing the mean of each column of `A` to the array containing the mean of each row of `C` and print the result.
    
    - Add the array containing the mean of each row of `B` to the array containing the mean of each row of `C` which is then added to the array containing the mean of each column of `C` and print the result.
    
- In the Markdown cell that follows the code cell, explain why we cannot add the array containing the mean of each row of `A` to the array containing the mean of each row of `C`.

In [58]:

x=np.mean(A, axis=1)
print(x)
n= np.mean(C,axis=1)
print(n)
y=np.mean(B,axis=0)
z=x+y
print(z)
#


[2. 5.]
[2. 5. 8.]
[5. 9.]


In [55]:
a= np.mean(A,axis=0)
b= np.mean(B,axis=1)
z=a+b
print(z)

[ 4.  7. 10.]


In [54]:
a= np.mean(A,axis=0)
b= np.mean(C,axis=1)

z=a+b

print(z)

[ 4.5  8.5 12.5]


<span style='background:rgba(255,255,0, 0.25); color:black'> Use this Markdown cell to explain why we cannot add the mean of each row of `A` to the mean of each row of `C`. </span>

In [57]:
a= np.mean(B,axis=1)
b= np.mean(C,axis=1)
z=a+b
q= np.mean(C,axis=0)
h= q+z
print(h)

[ 7.5 13.5 19.5]


#x=np.mean(A, axis=1)
print(x)
n= np.mean(C,axis=1)
print(n)


---

##  <mark>Activity 3: Some practice with transposes and array slicing</mark> 


- In the code cell below, use array slicing to do the following:

    - Add `A` to the first two rows of `C` and print the result.
    
    - Add the transpose of `A` to the first two columns of `C` and print the result. 
    
    - Add `B` to the last two columns of `C` and print the result.
    
    - Even though they are not the same shape, add the last column of the transpose of `A` (as a 2D array) to the last two columns of `C` and print the result. *Hint: `[:,-1:]` and `[:,-1]` do not produce the same array shapes. One will produce the desired 2D array shape.*

In [60]:
#arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
#print(arr)

#print(arr[0:2, 1:4])
sum_a = A + C[0:2]
print(sum_a)


[[ 2  4  6]
 [ 8 10 12]]


In [76]:
arr1  = np.transpose(A)

b = arr1+ C[:, 0:2]
print(b)


[[ 2  6]
 [ 6 10]
 [10 14]]


In [78]:
last_two= (C[:,-2::])

c= B + last_two
print(c)

[[ 3  5]
 [ 8 10]
 [13 15]]


In [79]:
arr1  = np.transpose(A)
last_column_A=arr1[:,-1:]

print(last_column_A+last_two)


[[ 6  7]
 [10 11]
 [14 15]]


End of Activity 3.

---